name: confess
description: My new Flutter app
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  alice: null
  appwrite: ^8.1.0
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: null
  go_router: ^10.0.0
  google_fonts: null
  hoverover: ^0.1.1
  intl: ^0.17.0
  logger: ^1.4.0
  lottie: null
  responsive_builder: ^0.7.0
  responsive_framework: null
  url_strategy: ^0.2.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: null
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: null
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - .env
